"use strict";
class TurboRaceApp {
  constructor(){this.canvas=document.getElementById("jogo");this.ctx=this.canvas.getContext("2d");this.camadaHtml=document.getElementById("camada-html");this.avisoOrientacao=document.getElementById("aviso-orientacao");this.save=new SaveManager();this.sound=new SoundManager(this.save);this.largura=1;this.altura=1;this.tela=null;this.ultimo=performance.now();this.telas={menu:()=>new TelaDeMenu(this),worldtour:()=>new TelaWorldTour(this),garagem:()=>new TelaDaGaragem(this),config:()=>new TelaDeConfiguracoes(this),online:()=>new TelaOnline(this),corrida:()=>new TelaDeCorrida(this),video:()=>new TelaDeVideo(this)};this._eventos();this._orientacao();this.redimensionar();}
  _eventos(){window.addEventListener("resize",()=>this.redimensionar());document.addEventListener("visibilitychange",()=>document.hidden?this.sound.pauseAll():this.sound.resumeAll());const nomes={pointerdown:"baixo",pointermove:"move",pointerup:"cima",pointercancel:"cima"};for(const tipo of Object.keys(nomes)){this.canvas.addEventListener(tipo,e=>{const rolagemNativa=!!this.tela?.usaRolagemNativa;if(!rolagemNativa)e.preventDefault();if(tipo==="pointerdown"){this.sound.destravar();if(!rolagemNativa)try{if(this.canvas.setPointerCapture&&e.pointerId!=null)this.canvas.setPointerCapture(e.pointerId);}catch(_){/* alguns navegadores recusam captura em toque sintetico */}}if(rolagemNativa&&tipo==="pointermove")return;const r=this.canvas.getBoundingClientRect();const x=(e.clientX-r.left)*this.largura/r.width,y=(e.clientY-r.top)*this.altura/r.height;const nome=rolagemNativa&&tipo==="pointercancel"?"cancelar":nomes[tipo];this.tela?.aoApontar?.(nome,x,y,e);});}window.addEventListener("keydown",e=>this.tela?.aoTeclar?.(e,true));window.addEventListener("keyup",e=>this.tela?.aoTeclar?.(e,false));this.canvas.addEventListener("wheel",e=>{if(this.tela?.usaRolagemNativa)return;e.preventDefault();this.tela?.aoGirarRoda?.(e.deltaY);},{passive:false});}
  redimensionar(){const d=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.largura=Math.max(320,Math.round(r.width*d));this.altura=Math.max(180,Math.round(r.height*d));this.canvas.width=this.largura;this.canvas.height=this.altura;this.tela?.medir?.(this.largura,this.altura);}
  _orientacao(){if(!this.avisoOrientacao)return;this.avisoOrientacao.addEventListener("click",async()=>{try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch(_){}try{if(screen.orientation?.lock)await screen.orientation.lock("landscape");}catch(_){};});}
  _limparRolagemDeMenu(){document.documentElement.classList.remove("configuracoes-rolaveis");document.body.classList.remove("configuracoes-rolaveis");document.querySelectorAll("body > .rolagem-nativa").forEach(e=>e.remove());document.body.scrollTop=0;document.documentElement.scrollTop=0;window.scrollTo(0,0);}
  irPara(nome,parametros){this.tela?.sair?.();this._limparRolagemDeMenu();this.camadaHtml.replaceChildren();const fabrica=this.telas[nome]||this.telas.menu;this.tela=fabrica();this.tela.entrar?.(parametros||{});this.tela.medir?.(this.largura,this.altura);}
  iniciar(){this.irPara(this.save.introSeen?"menu":"video",this.save.introSeen?{}:{tipo:"intro",depois:"menu"});requestAnimationFrame(t=>this.loop(t));}
  loop(agora){const dt=Math.min(.05,(agora-this.ultimo)/1000||0);this.ultimo=agora;this.tela?.update?.(dt);this.ctx.clearRect(0,0,this.largura,this.altura);this.tela?.render?.(this.ctx,this.largura,this.altura);requestAnimationFrame(t=>this.loop(t));}
}
window.TurboRaceApp=TurboRaceApp;
window.addEventListener("DOMContentLoaded",()=>{const p=document.getElementById("progresso");Assets.carregarEssenciais((n,t)=>p.textContent="Carregando "+n+"/"+t).then(()=>{document.getElementById("carregando").classList.add("oculto");window.app=new TurboRaceApp();app.iniciar();});});
