(function () {
  'use strict';
  var API = 'https://vmgames-comunidade.onrender.com';
  var root = document.querySelector('[data-interacoes]'); if (!root) return;
  var page = root.dataset.interacoes, likeButton = root.querySelector('[data-curtir]'), likeCount = root.querySelector('[data-curtidas]'), form = root.querySelector('[data-comentario-form]'), list = root.querySelector('[data-comentarios]'), status = root.querySelector('[data-comentario-status]');
  function visitor() { var key = 'vmgames-visitor', value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID ? crypto.randomUUID() : Date.now() + '-' + Math.random().toString(16).slice(2); localStorage.setItem(key, value); } return value; }
  function escapeText(value) { var span = document.createElement('span'); span.textContent = value; return span.innerHTML; }
  function date(value) { return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
  function renderComments(comments) { if (!comments.length) { list.innerHTML = '<p class="sem-comentarios">Seja a primeira pessoa a comentar.</p>'; return; } list.innerHTML = comments.map(function (c) { return '<article class="comentario"><header><strong>' + escapeText(c.name) + '</strong><time datetime="' + escapeText(c.created_at) + '">' + date(c.created_at) + '</time></header><p>' + escapeText(c.body) + '</p></article>'; }).join(''); }
  function load() { fetch(API + '/v1/interactions?page=' + encodeURIComponent(page)).then(function (r) { if (!r.ok) throw new Error(); return r.json(); }).then(function (data) { likeCount.textContent = data.likes; renderComments(data.comments); }).catch(function () { status.textContent = 'As interações estão despertando. Tente novamente em instantes.'; }); }
  likeButton.addEventListener('click', function () { likeButton.disabled = true; fetch(API + '/v1/likes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ page: page, visitor: visitor() }) }).then(function (r) { return r.json().then(function (x) { if (!r.ok) throw new Error(x.erro); return x; }); }).then(function (data) { likeCount.textContent = data.likes; likeButton.classList.add('curtido'); likeButton.setAttribute('aria-pressed', 'true'); }).catch(function () { status.textContent = 'Não foi possível registrar a curtida agora.'; }).finally(function () { likeButton.disabled = false; }); });
  root.addEventListener('click', function (e) { var share = e.target.closest('[data-compartilhar-nativo]'); if (!share) return; var data = { title: document.title, text: document.querySelector('meta[name="description"]').content, url: location.href }; if (navigator.share) navigator.share(data).catch(function () {}); else navigator.clipboard.writeText(location.href).then(function () { share.textContent = 'Link copiado'; }); });
  form.addEventListener('submit', function (e) { e.preventDefault(); var button = form.querySelector('button[type="submit"]'); button.disabled = true; status.textContent = 'Enviando…'; var data = new FormData(form); fetch(API + '/v1/comments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ page: page, name: data.get('name'), body: data.get('body'), website: data.get('website') }) }).then(function (r) { return r.json().then(function (x) { if (!r.ok) throw new Error(x.erro); return x; }); }).then(function () { form.reset(); status.textContent = 'Comentário publicado.'; load(); }).catch(function (err) { status.textContent = err.message || 'Não foi possível enviar.'; }).finally(function () { button.disabled = false; }); });
  load();
})();
