(function(){
  "use strict";
  var API="https://vmgames-comunidade.onrender.com", token=sessionStorage.getItem("vmgames_admin_token")||"";
  var login=document.getElementById("login"),painel=document.getElementById("painel"),sair=document.getElementById("sair"),form=document.getElementById("login-form"),loginStatus=document.getElementById("login-status"),painelStatus=document.getElementById("painel-status"),lista=document.getElementById("lista"),filtro=document.getElementById("filtro");
  function text(value){return document.createTextNode(String(value||""));}
  function auth(){return {Authorization:"Bearer "+token};}
  async function request(path,options){var response=await fetch(API+path,options),data=await response.json().catch(function(){return{};});if(!response.ok){if(response.status===401)logout();throw new Error(data.erro||"Não foi possível concluir.");}return data;}
  function showPanel(){login.hidden=true;painel.hidden=false;sair.hidden=false;load();}
  function logout(){token="";sessionStorage.removeItem("vmgames_admin_token");painel.hidden=true;sair.hidden=true;login.hidden=false;form.reset();}
  function metric(id,value){document.getElementById(id).textContent=Number(value||0).toLocaleString("pt-BR");}
  function renderComments(comments){lista.replaceChildren();if(!comments.length){var empty=document.createElement("p");empty.className="vazio";empty.textContent="Nenhum comentário neste filtro.";lista.appendChild(empty);return;}comments.forEach(function(item){var card=document.createElement("article"),content=document.createElement("div"),header=document.createElement("header"),name=document.createElement("strong"),page=document.createElement("span"),date=document.createElement("time"),body=document.createElement("p"),actions=document.createElement("div"),button=document.createElement("button");card.className="comentario";name.appendChild(text(item.name));page.className="pagina";page.appendChild(text(item.page_key));date.dateTime=item.created_at;date.appendChild(text(new Date(item.created_at).toLocaleString("pt-BR")));header.append(name,page,date);body.appendChild(text(item.body));content.append(header,body);actions.className="acoes";button.className="acao "+(item.status==="hidden"?"aprovar":"ocultar");button.type="button";button.textContent=item.status==="hidden"?"Aprovar":"Ocultar";button.addEventListener("click",function(){changeStatus(item.id,item.status==="hidden"?"approved":"hidden",button);});actions.appendChild(button);card.append(content,actions);lista.appendChild(card);});}
  async function load(){painelStatus.textContent="Atualizando…";try{var results=await Promise.all([request("/v1/admin/summary",{headers:auth()}),request("/v1/admin/comments?status="+encodeURIComponent(filtro.value),{headers:auth()})]);metric("total-curtidas",results[0].likes);metric("total-publicados",results[0].approved);metric("total-ocultos",results[0].hidden);metric("total-paginas",results[0].pages);renderComments(results[1].comments);painelStatus.textContent="";}catch(error){painelStatus.textContent=error.message;}}
  async function changeStatus(id,status,button){button.disabled=true;try{await request("/v1/admin/comments/"+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json"},auth()),body:JSON.stringify({status:status})});await load();}catch(error){painelStatus.textContent=error.message;button.disabled=false;}}
  form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button"),data=new FormData(form);button.disabled=true;loginStatus.textContent="Entrando…";try{var result=await request("/v1/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:data.get("username"),password:data.get("password")})});token=result.token;sessionStorage.setItem("vmgames_admin_token",token);loginStatus.textContent="";form.reset();showPanel();}catch(error){loginStatus.textContent=error.message;}finally{button.disabled=false;}});
  sair.addEventListener("click",logout);document.getElementById("atualizar").addEventListener("click",load);filtro.addEventListener("change",load);if(token)showPanel();
})();
